import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Disclaimer - GPA Converter to 4.0 Scale',
  description: 'This tool provides reference only, not official academic certification.',
  keywords: 'GPA converter disclaimer',
}

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#E3F2FD] to-white py-12">
      <div className="container mx-auto px-4 max-w-3xl">
        {/* Header */}
        <header className="text-center mb-12">
          <h1 className="text-3xl font-bold text-[#333333] mb-2">Disclaimer</h1>
          <p className="text-lg text-gray-600">GPA Converter to 4.0 Scale</p>
        </header>

        {/* Main Content */}
        <main className="bg-white rounded-xl shadow-lg p-8">
          <div className="space-y-6">
            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">1. General Disclaimer</h2>
              <p className="text-gray-700 leading-relaxed">
                The GPA Converter tool is provided for informational purposes only and is not intended to be used as official academic certification or advice. We do not guarantee the accuracy, completeness, or reliability of any information provided by this tool.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">2. Accuracy of Results</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                While we strive to provide accurate conversion results, different educational institutions may have their own GPA conversion formulas and policies. The results generated by our tool should be used as a general reference only and may not match the exact conversion used by any specific institution.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                This tool supports multiple GPA scales, including Chinese 100-point scale, Chinese 5-point scale, UK 7-point scale, Australian 4-point scale, Letter Grade, Canadian 4-point scale, European ECTS, Japanese GPA, Korean GPA, and Indian GPA. All conversion results are based on general standards and may vary by institution.
              </p>
              <p className="text-gray-700 leading-relaxed">
                We strongly recommend that you verify any GPA conversion with the specific institution or organization that requires it.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">3. No Warranty</h2>
              <p className="text-gray-700 leading-relaxed">
                The GPA Converter tool is provided "as is" without any warranties, express or implied. We do not warrant that the tool will be uninterrupted, error-free, or free of viruses or other harmful components.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">4. Limitation of Liability</h2>
              <p className="text-gray-700 leading-relaxed">
                In no event shall GPA Converter or its owners, operators, or affiliates be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of this tool, even if advised of the possibility of such damages.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">5. Use of the Tool</h2>
              <p className="text-gray-700 leading-relaxed">
                By using the GPA Converter tool, you agree to use it only for lawful purposes and in accordance with all applicable laws and regulations. You are solely responsible for any decisions or actions taken based on the information provided by this tool.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">6. Changes to the Tool</h2>
              <p className="text-gray-700 leading-relaxed">
                We reserve the right to modify, suspend, or discontinue the GPA Converter tool at any time without prior notice. We may also update the conversion formulas or rules without notice.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">7. Third-Party Links</h2>
              <p className="text-gray-700 leading-relaxed">
                Our website may contain links to third-party websites. We are not responsible for the content, accuracy, or reliability of any third-party websites or services linked to or from our website.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">8. Governing Law</h2>
              <p className="text-gray-700 leading-relaxed">
                This disclaimer shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">9. Changes to This Disclaimer</h2>
              <p className="text-gray-700 leading-relaxed">
                We may update this Disclaimer from time to time. Any changes will be posted on this page with an updated effective date. We encourage you to review this Disclaimer periodically for any changes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#333333] mb-4">10. Effective Date</h2>
              <p className="text-gray-700 leading-relaxed">
                This Disclaimer is effective as of February 25, 2026.
              </p>
            </section>
          </div>
        </main>

        {/* Footer */}
        <footer className="mt-12 text-center text-sm text-gray-500">
          <div className="flex justify-center gap-6">
            <a href="/" className="hover:text-[#FFB74D] transition-colors">Home</a>
            <a href="/privacy" className="hover:text-[#FFB74D] transition-colors">Privacy Policy</a>
          </div>
        </footer>
      </div>
    </div>
  )
}